# Generated by Django 4.1.4 on 2023-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('prix', models.IntegerField(max_length=200)),
                ('carburant', models.CharField(choices=[('diesel', 'diesel'), ('essance', 'essance')], max_length=200)),
                ('marque', models.CharField(max_length=200)),
            ],
        ),
    ]
