# Generated by Django 4.1.4 on 2023-01-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
